//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MvcAndEf.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MobiBookEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MobiBookEntities object using the connection string found in the 'MobiBookEntities' section of the application configuration file.
        /// </summary>
        public MobiBookEntities() : base("name=MobiBookEntities", "MobiBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MobiBookEntities object.
        /// </summary>
        public MobiBookEntities(string connectionString) : base(connectionString, "MobiBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MobiBookEntities object.
        /// </summary>
        public MobiBookEntities(EntityConnection connection) : base(connection, "MobiBookEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MobiBookModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="pK_SearchId">Initial value of the PK_SearchId property.</param>
        /// <param name="isAllYouCanRead">Initial value of the IsAllYouCanRead property.</param>
        public static Product CreateProduct(global::System.Int64 pK_SearchId, global::System.Boolean isAllYouCanRead)
        {
            Product product = new Product();
            product.PK_SearchId = pK_SearchId;
            product.IsAllYouCanRead = isAllYouCanRead;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PK_SearchId
        {
            get
            {
                return _PK_SearchId;
            }
            set
            {
                if (_PK_SearchId != value)
                {
                    OnPK_SearchIdChanging(value);
                    ReportPropertyChanging("PK_SearchId");
                    _PK_SearchId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PK_SearchId");
                    OnPK_SearchIdChanged();
                }
            }
        }
        private global::System.Int64 _PK_SearchId;
        partial void OnPK_SearchIdChanging(global::System.Int64 value);
        partial void OnPK_SearchIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PK_ProductID
        {
            get
            {
                return _PK_ProductID;
            }
            set
            {
                OnPK_ProductIDChanging(value);
                ReportPropertyChanging("PK_ProductID");
                _PK_ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PK_ProductID");
                OnPK_ProductIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PK_ProductID;
        partial void OnPK_ProductIDChanging(Nullable<global::System.Int32> value);
        partial void OnPK_ProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductCode
        {
            get
            {
                return _ProductCode;
            }
            set
            {
                OnProductCodeChanging(value);
                ReportPropertyChanging("ProductCode");
                _ProductCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductCode");
                OnProductCodeChanged();
            }
        }
        private global::System.String _ProductCode;
        partial void OnProductCodeChanging(global::System.String value);
        partial void OnProductCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BookProvider
        {
            get
            {
                return _BookProvider;
            }
            set
            {
                OnBookProviderChanging(value);
                ReportPropertyChanging("BookProvider");
                _BookProvider = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BookProvider");
                OnBookProviderChanged();
            }
        }
        private Nullable<global::System.Int32> _BookProvider;
        partial void OnBookProviderChanging(Nullable<global::System.Int32> value);
        partial void OnBookProviderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WebImage
        {
            get
            {
                return _WebImage;
            }
            set
            {
                OnWebImageChanging(value);
                ReportPropertyChanging("WebImage");
                _WebImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WebImage");
                OnWebImageChanged();
            }
        }
        private global::System.String _WebImage;
        partial void OnWebImageChanging(global::System.String value);
        partial void OnWebImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WapImage
        {
            get
            {
                return _WapImage;
            }
            set
            {
                OnWapImageChanging(value);
                ReportPropertyChanging("WapImage");
                _WapImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WapImage");
                OnWapImageChanged();
            }
        }
        private global::System.String _WapImage;
        partial void OnWapImageChanging(global::System.String value);
        partial void OnWapImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZoomWebImage
        {
            get
            {
                return _ZoomWebImage;
            }
            set
            {
                OnZoomWebImageChanging(value);
                ReportPropertyChanging("ZoomWebImage");
                _ZoomWebImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZoomWebImage");
                OnZoomWebImageChanged();
            }
        }
        private global::System.String _ZoomWebImage;
        partial void OnZoomWebImageChanging(global::System.String value);
        partial void OnZoomWebImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZoomWapImage
        {
            get
            {
                return _ZoomWapImage;
            }
            set
            {
                OnZoomWapImageChanging(value);
                ReportPropertyChanging("ZoomWapImage");
                _ZoomWapImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZoomWapImage");
                OnZoomWapImageChanged();
            }
        }
        private global::System.String _ZoomWapImage;
        partial void OnZoomWapImageChanging(global::System.String value);
        partial void OnZoomWapImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProductType
        {
            get
            {
                return _ProductType;
            }
            set
            {
                OnProductTypeChanging(value);
                ReportPropertyChanging("ProductType");
                _ProductType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductType");
                OnProductTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _ProductType;
        partial void OnProductTypeChanging(Nullable<global::System.Int32> value);
        partial void OnProductTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsAdultContent
        {
            get
            {
                return _IsAdultContent;
            }
            set
            {
                OnIsAdultContentChanging(value);
                ReportPropertyChanging("IsAdultContent");
                _IsAdultContent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdultContent");
                OnIsAdultContentChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsAdultContent;
        partial void OnIsAdultContentChanging(Nullable<global::System.Boolean> value);
        partial void OnIsAdultContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LanguageID
        {
            get
            {
                return _LanguageID;
            }
            set
            {
                OnLanguageIDChanging(value);
                ReportPropertyChanging("LanguageID");
                _LanguageID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LanguageID");
                OnLanguageIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LanguageID;
        partial void OnLanguageIDChanging(Nullable<global::System.Int32> value);
        partial void OnLanguageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Fk_GenreID
        {
            get
            {
                return _Fk_GenreID;
            }
            set
            {
                OnFk_GenreIDChanging(value);
                ReportPropertyChanging("Fk_GenreID");
                _Fk_GenreID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fk_GenreID");
                OnFk_GenreIDChanged();
            }
        }
        private Nullable<global::System.Int32> _Fk_GenreID;
        partial void OnFk_GenreIDChanging(Nullable<global::System.Int32> value);
        partial void OnFk_GenreIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAllYouCanRead
        {
            get
            {
                return _IsAllYouCanRead;
            }
            set
            {
                OnIsAllYouCanReadChanging(value);
                ReportPropertyChanging("IsAllYouCanRead");
                _IsAllYouCanRead = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAllYouCanRead");
                OnIsAllYouCanReadChanged();
            }
        }
        private global::System.Boolean _IsAllYouCanRead;
        partial void OnIsAllYouCanReadChanging(global::System.Boolean value);
        partial void OnIsAllYouCanReadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsRental
        {
            get
            {
                return _IsRental;
            }
            set
            {
                OnIsRentalChanging(value);
                ReportPropertyChanging("IsRental");
                _IsRental = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRental");
                OnIsRentalChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsRental;
        partial void OnIsRentalChanging(Nullable<global::System.Boolean> value);
        partial void OnIsRentalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Isr
        {
            get
            {
                return _Isr;
            }
            set
            {
                OnIsrChanging(value);
                ReportPropertyChanging("Isr");
                _Isr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Isr");
                OnIsrChanged();
            }
        }
        private Nullable<global::System.Boolean> _Isr;
        partial void OnIsrChanging(Nullable<global::System.Boolean> value);
        partial void OnIsrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsFreeGiveAway
        {
            get
            {
                return _IsFreeGiveAway;
            }
            set
            {
                OnIsFreeGiveAwayChanging(value);
                ReportPropertyChanging("IsFreeGiveAway");
                _IsFreeGiveAway = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFreeGiveAway");
                OnIsFreeGiveAwayChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsFreeGiveAway;
        partial void OnIsFreeGiveAwayChanging(Nullable<global::System.Boolean> value);
        partial void OnIsFreeGiveAwayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsBSVFree
        {
            get
            {
                return _IsBSVFree;
            }
            set
            {
                OnIsBSVFreeChanging(value);
                ReportPropertyChanging("IsBSVFree");
                _IsBSVFree = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBSVFree");
                OnIsBSVFreeChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsBSVFree;
        partial void OnIsBSVFreeChanging(Nullable<global::System.Boolean> value);
        partial void OnIsBSVFreeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsShared
        {
            get
            {
                return _IsShared;
            }
            set
            {
                OnIsSharedChanging(value);
                ReportPropertyChanging("IsShared");
                _IsShared = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsShared");
                OnIsSharedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsShared;
        partial void OnIsSharedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsSharedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keywords
        {
            get
            {
                return _Keywords;
            }
            set
            {
                OnKeywordsChanging(value);
                ReportPropertyChanging("Keywords");
                _Keywords = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Keywords");
                OnKeywordsChanged();
            }
        }
        private global::System.String _Keywords;
        partial void OnKeywordsChanging(global::System.String value);
        partial void OnKeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _Price;
        partial void OnPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Point
        {
            get
            {
                return _Point;
            }
            set
            {
                OnPointChanging(value);
                ReportPropertyChanging("Point");
                _Point = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Point");
                OnPointChanged();
            }
        }
        private Nullable<global::System.Int32> _Point;
        partial void OnPointChanging(Nullable<global::System.Int32> value);
        partial void OnPointChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ConvertedPoints
        {
            get
            {
                return _ConvertedPoints;
            }
            set
            {
                OnConvertedPointsChanging(value);
                ReportPropertyChanging("ConvertedPoints");
                _ConvertedPoints = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConvertedPoints");
                OnConvertedPointsChanged();
            }
        }
        private Nullable<global::System.Int32> _ConvertedPoints;
        partial void OnConvertedPointsChanging(Nullable<global::System.Int32> value);
        partial void OnConvertedPointsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PublishDate
        {
            get
            {
                return _PublishDate;
            }
            set
            {
                OnPublishDateChanging(value);
                ReportPropertyChanging("PublishDate");
                _PublishDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PublishDate");
                OnPublishDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PublishDate;
        partial void OnPublishDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPublishDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> MappedDate
        {
            get
            {
                return _MappedDate;
            }
            set
            {
                OnMappedDateChanging(value);
                ReportPropertyChanging("MappedDate");
                _MappedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MappedDate");
                OnMappedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _MappedDate;
        partial void OnMappedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnMappedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SupportedDevice
        {
            get
            {
                return _SupportedDevice;
            }
            set
            {
                OnSupportedDeviceChanging(value);
                ReportPropertyChanging("SupportedDevice");
                _SupportedDevice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SupportedDevice");
                OnSupportedDeviceChanged();
            }
        }
        private global::System.String _SupportedDevice;
        partial void OnSupportedDeviceChanging(global::System.String value);
        partial void OnSupportedDeviceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> HasProductIdentifier
        {
            get
            {
                return _HasProductIdentifier;
            }
            set
            {
                OnHasProductIdentifierChanging(value);
                ReportPropertyChanging("HasProductIdentifier");
                _HasProductIdentifier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasProductIdentifier");
                OnHasProductIdentifierChanged();
            }
        }
        private Nullable<global::System.Boolean> _HasProductIdentifier;
        partial void OnHasProductIdentifierChanging(Nullable<global::System.Boolean> value);
        partial void OnHasProductIdentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Int32> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Int32> value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DefaultStoryID
        {
            get
            {
                return _DefaultStoryID;
            }
            set
            {
                OnDefaultStoryIDChanging(value);
                ReportPropertyChanging("DefaultStoryID");
                _DefaultStoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefaultStoryID");
                OnDefaultStoryIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DefaultStoryID;
        partial void OnDefaultStoryIDChanging(Nullable<global::System.Int32> value);
        partial void OnDefaultStoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AvgRating
        {
            get
            {
                return _AvgRating;
            }
            set
            {
                OnAvgRatingChanging(value);
                ReportPropertyChanging("AvgRating");
                _AvgRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AvgRating");
                OnAvgRatingChanged();
            }
        }
        private Nullable<global::System.Int32> _AvgRating;
        partial void OnAvgRatingChanging(Nullable<global::System.Int32> value);
        partial void OnAvgRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PurchaseCount
        {
            get
            {
                return _PurchaseCount;
            }
            set
            {
                OnPurchaseCountChanging(value);
                ReportPropertyChanging("PurchaseCount");
                _PurchaseCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PurchaseCount");
                OnPurchaseCountChanged();
            }
        }
        private Nullable<global::System.Int32> _PurchaseCount;
        partial void OnPurchaseCountChanging(Nullable<global::System.Int32> value);
        partial void OnPurchaseCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StoryCount
        {
            get
            {
                return _StoryCount;
            }
            set
            {
                OnStoryCountChanging(value);
                ReportPropertyChanging("StoryCount");
                _StoryCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StoryCount");
                OnStoryCountChanged();
            }
        }
        private Nullable<global::System.Int32> _StoryCount;
        partial void OnStoryCountChanging(Nullable<global::System.Int32> value);
        partial void OnStoryCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> HasStorySample
        {
            get
            {
                return _HasStorySample;
            }
            set
            {
                OnHasStorySampleChanging(value);
                ReportPropertyChanging("HasStorySample");
                _HasStorySample = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HasStorySample");
                OnHasStorySampleChanged();
            }
        }
        private Nullable<global::System.Boolean> _HasStorySample;
        partial void OnHasStorySampleChanging(Nullable<global::System.Boolean> value);
        partial void OnHasStorySampleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsBitway
        {
            get
            {
                return _IsBitway;
            }
            set
            {
                OnIsBitwayChanging(value);
                ReportPropertyChanging("IsBitway");
                _IsBitway = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBitway");
                OnIsBitwayChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsBitway;
        partial void OnIsBitwayChanging(Nullable<global::System.Boolean> value);
        partial void OnIsBitwayChanged();

        #endregion
    
    }

    #endregion
    
}
